"""Initial migration

Revision ID: f66c185142cd
Revises: 5fe1617eb8ad
Create Date: 2025-04-05 03:17:29.525148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f66c185142cd'
down_revision: Union[str, None] = '5fe1617eb8ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('mic', sa.Integer(), server_default='0'))
    op.add_column('categories', sa.Column('tab', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'tab')
    op.drop_column('categories', 'mic')
    # ### end Alembic commands ###